name: Publish Extension
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "src/**"
      - ".github/workflows/main.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.SAMEPAGE_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SAMEPAGE_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npx samepage build
      - name: package
        run: zip -q dist/logseq.zip README.md dist/index.js dist/index.css dist/normalize.css dist/blueprint.css dist/blueprint-icons.css index.html logo.svg package.json
      - name: deploy
        run: |
          VERSION=$(cat package.json | grep version | cut -d ':' -f 2 | cut -d '"' -f 2)
          aws s3 cp dist/logseq.zip s3://samepage.network/extensions/logseq.zip --metadata Version=$VERSION
