name: Publish Web App
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "src/**"
      - ".github/workflows/main.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: node scripts/build.js
      - name: package
        run: zip -jq dist/logseq.zip README.md dist/main.js dist/main.css index.html logo.svg package.json
      - name: deploy
        run: aws s3 cp dist/logseq.zip s3://samepage.network/extensions/logseq.zip
